const translations = {
    kk: {
        app_title: "ҒЫЛЫМИ ЗЕРТТЕУ ТЕХНОЛОГИЯСЫ",
        user_default: "Пайдаланушы",
        id_unknown: "ID: Белгісіз",
        btn_logout: "Шығу (Logout)",
        btn_login_trigger: "Кіру / Тіркелу",
        nav_pubs: "Жарияланымдар",
        nav_settings: "БАПТАУЛАР",
        btn_enter: "КІРУ",
        title_query: "Ғылыми кеңесші",
        desc_query: "Сұрақтарыңыз бен күмәндарыңызды шешіңіз.",
        title_methodology: "Әдістемелік нұсқаулықтар",
        desc_methodology: "Ғылыми жобалардың әдіснамасы туралы көбірек біліңіз.",
        title_search: "Жобаларды іздеу",
        desc_search: "Байланысты зерттеу жобаларын табыңыз.",
        title_plagiarism: "Антиплагиат",
        desc_plagiarism: "Мәтінді плагиатқа тексеріңіз.",
        title_infographic: "Инфографика құру",
        desc_infographic: "Кәсіби кестелер мен диаграммалар жасаңыз.",
        title_experiments: "Эксперимент журналдары",
        desc_experiments: "Деректерді жүктеп, эксперименттерді бақылаңыз.",
        auth_title_login: "Кіру",
        auth_ph_user: "Логин (Username)",
        auth_ph_pass: "Құпия сөз (Password)",
        auth_btn_login: "Кіру",
        auth_btn_register: "Тіркелу",
        auth_toggle_login: "Аккаунтыңыз бар ма? Кіру",
        auth_toggle_register: "Аккаунтыңыз жоқ па? Тіркелу",
        auth_err_fields: "Барлық өрістерді толтырыңыз.",
        auth_wait: "Күте тұрыңыз...",
        auth_err_server: "Қате орын алды (Сервермен байланыс жоқ).",
        chat_placeholder: "Мәтін енгізіңіз...",
        search_title: "Тақырып бойынша мақалалар іздеу",
        search_desc: "Зерттеуіңізге қатысты 5 ағылшынша мақаланы табу үшін тақырыпты енгізіңіз.",
        search_btn: "ІЗДЕУ",
        header_methodology: "Ғылыми мақала жазу",
        method_s1: "1-қадам: Ашық мәселе құру",
        method_d1: "Ғылыми мақаланы құрыңыз және әдебиеттерге шолу жасаңыз.",
        method_s2: "2-қадам: Диссертация құру",
        method_d2: "Негізгі мақаланы құру үшін тиісті процестерді өлшеңіз.",
        method_s3: "3-қадам: Әдістемені жобалау",
        method_d3: "Негізгі модельдерді дайындаңыз және нақты схема құрыңыз.",
        method_s4: "4-қадам: Жобаны жазу",
        method_d4: "Ғылыми мақала жасау үшін алғашқы жобаны жазыңыз.",
        method_s5: "5-қадам: Өңдеу және пішімдеу",
        method_d5: "Соңғы өңдеулерді аяқтаңыз және стандартты пішімдеуді қолданыңыз.",
        plag_card_title: "МӘТІНДІ ТЕКСЕРУ",
        plag_card_desc: "Төмендегі өріске мәтініңізді қойыңыз (макс. 5000 таңба).",
        plag_btn: "ТЕКСЕРУДІ БАСТАУ",
        plag_score: "ОРИГИНАЛДЫҚ",
        plag_status: "КҮТУДЕ...",
        plag_ai_tips: "AI КЕҢЕСТЕРІ",
        header_infographics: "Инфографика конструкторы",
        info_labels: "Деректердің атауы (Labels)",
        info_values: "Мәндері (Values)",
        info_type: "Диаграмма түрі",
        info_type_bar: "Баған",
        info_type_line: "Сызық",
        info_type_pie: "Дөңгелек",
        info_type_radar: "Радар",
        info_palette: "Түстер палитрасы",
        info_btn_dl: "PNG жүктеп алу",
        header_pubs: "Менің жарияланымдарым",
        pubs_drag: "Файлды осында сүйреңіз немесе",
        pubs_select: "таңдаңыз",
        pubs_refresh: "Жаңарту",
        pubs_list: "Файлдар тізімі",
        header_comingsoon: "Әзірленуде",
        comingsoon_title: "Жақында",
        comingsoon_desc: "Бұл модуль әзірлену үстінде.",
        header_settings: "Баптаулар",
        set_darkmode: "Түнгі режим",
        set_darkmode_desc: "Интерфейс түсін күңгіртке ауыстыру",
        set_font: "Чат шрифті",
        set_font_desc: "Сұрақ орталығындағы мәтін өлшемі",
        set_lang: "Тіл (Language)",
        set_lang_desc: "Интерфейс тілін таңдаңыз",
        chart_dataset: "Деректер жиынтығы",
        search_loading: "Ғылыми мәліметтер ізделуде...",
        search_analyzing: "Модель тақырыбыңызды талдап жатыр.",
        search_err_parse: "Мәліметтерді өңдеу кезінде қате орын алды (JSON Format).",
        search_no_title: "Тақырыпсыз мақала",
        search_no_author: "Белгісіз автор",
        search_no_year: "Жыл көрсетілмеген",
        search_read_more: "Толық оқу",
        search_err_fetch: "Серверден мақала алу мүмкін болмады.",
        search_err_network: "Желі қателігі орын алды.",
        ai_no_response: "Жауап жоқ.",
        plag_alert_empty: "Мәтінді енгізіңіз!",
        plag_analyzing: "ТАЛДАУ ЖАСАЛУДА...",
        plag_calculating: "Есептелуде...",
        plag_searching: "ІЗДЕУДЕ...",
        plag_ai_analyzing: "AI мәтін құрылымын талдап жатыр...",
        plag_err_parse: "Сервер жауабын өңдеу мүмкін болмады.",
        plag_err_network: "Желілік қате орын алды.",
        pub_alert_login: "Жүктеу үшін алдымен жеке кабинетіңізге кіріңіз!",
        pub_reading: "Файл оқылуда...",
        pub_uploading: "Файл бұлтқа жүктелуде. Күте тұрыңыз...",
        pub_success: "Сәтті жүктелді!",
        pub_err_upload: "Жүктеу мүмкін болмады.",
        pub_err_network: "Байланыс қатесі.",
        pub_loading: "Жүктелуде...",
        pub_no_files: "Файлдар жүктелген жоқ.",
        pub_err_fetch: "Деректерді алу мүмкін болмады.",
        pub_download: "Жүктеу",
        auth_msg_prefix: "Қате: ",
        id_prefix: "ID: ",
        info_ph_labels: "Алма, Алмұрт, Шие",
        info_ph_values: "10, 20, 30",
        search_ph_topic: "Медицинадағы жасанды интеллект...",
        title_calculator: "Фото Калькулятор",
        desc_calculator: "Сурет арқылы есептерді шешу (Gemma 4).",
        calc_upload_prompt: "Суретті осы жерге жүктеңіз немесе түсіріңіз",
        calc_btn_solve: "ШЕШІМІН ТАБУ",
        calc_btn_clear: "ТАЗАЛАУ",
        calc_processing: "Gemma 4 есепті талдап жатыр...",
        calc_result_title: "Толық шешімі:",
        calc_err_no_img: "Алдымен суретті таңдаңыз!",
        calc_tab_stats: "Статистика",
        calc_tab_conv: "Түрлендіру",
        calc_stats_input: "Деректер (үтір немесе бос орын арқылы):",
        calc_btn_run: "Есептеу",
        calc_conv_type: "Түрі:"
    },
    ru: {
        app_title: "ТЕХНОЛОГИЯ НАУЧНЫХ ИССЛЕДОВАНИЙ",
        user_default: "Пользователь",
        id_unknown: "ID: Неизвестно",
        btn_logout: "Выйти (Logout)",
        btn_login_trigger: "Войти / Регистрация",
        nav_pubs: "Публикации",
        nav_settings: "НАСТРОЙКИ",
        btn_enter: "ВОЙТИ",
        title_query: "Научный советник",
        desc_query: "Решите ваши вопросы и сомнения.",
        title_methodology: "Методические указания",
        desc_methodology: "Узнайте больше о методологии научных проектов.",
        title_search: "Поиск проектов",
        desc_search: "Найдите связанные исследовательские проекты.",
        title_plagiarism: "Антиплагиат",
        desc_plagiarism: "Проверьте текст на плагиат.",
        title_infographic: "Создание инфографики",
        desc_infographic: "Создавайте профессиональные таблицы и диаграммы.",
        title_experiments: "Журналы экспериментов",
        desc_experiments: "Загружайте данные и отслеживайте эксперименты.",
        auth_title_login: "Войти",
        auth_ph_user: "Логин (Username)",
        auth_ph_pass: "Пароль (Password)",
        auth_btn_login: "Войти",
        auth_btn_register: "Зарегистрироваться",
        auth_toggle_login: "Уже есть аккаунт? Войти",
        auth_toggle_register: "Нет аккаунта? Зарегистрироваться",
        auth_err_fields: "Заполните все поля.",
        auth_wait: "Пожалуйста, подождите...",
        auth_err_server: "Произошла ошибка (нет связи с сервером).",
        chat_placeholder: "Введите текст...",
        search_title: "Поиск статей по теме",
        search_desc: "Введите тему, чтобы найти 5 англоязычных статей.",
        search_btn: "ПОИСК",
        header_methodology: "Написание научной статьи",
        method_s1: "Шаг 1: Формулировка проблемы",
        method_d1: "Сформулируйте проблему и сделайте обзор литературы.",
        method_s2: "Шаг 2: Создание диссертации",
        method_d2: "Измерьте соответствующие процессы для основной статьи.",
        method_s3: "Шаг 3: Проектирование методологии",
        method_d3: "Подготовьте базовые модели и составьте четкую схему.",
        method_s4: "Шаг 4: Написание проекта",
        method_d4: "Напишите первый черновик научной статьи.",
        method_s5: "Шаг 5: Редактирование",
        method_d5: "Завершите редактирование и примените форматирование.",
        plag_card_title: "ПРОВЕРКА ТЕКСТА",
        plag_card_desc: "Вставьте ваш текст в поле ниже (макс. 5000 символов).",
        plag_btn: "НАЧАТЬ ПРОВЕРКУ",
        plag_score: "ОРИГИНАЛЬНОСТЬ",
        plag_status: "ОЖИДАНИЕ...",
        plag_ai_tips: "СОВЕТЫ AI",
        header_infographics: "Конструктор инфографики",
        info_labels: "Названия (Labels)",
        info_values: "Значения (Values)",
        info_type: "Тип диаграммы",
        info_type_bar: "Бар",
        info_type_line: "Линия",
        info_type_pie: "Круг",
        info_type_radar: "Радар",
        info_palette: "Цветовая палитра",
        info_btn_dl: "Скачать PNG",
        header_pubs: "Мои публикации",
        pubs_drag: "Перетащите файл сюда или",
        pubs_select: "выберите",
        pubs_refresh: "Обновить",
        pubs_list: "Список файлов",
        header_comingsoon: "В разработке",
        comingsoon_title: "Скоро",
        comingsoon_desc: "Этот модуль находится в разработке.",
        header_settings: "Настройки",
        set_darkmode: "Ночной режим",
        set_darkmode_desc: "Переключение интерфейса в темный цвет",
        set_font: "Шрифт чата",
        set_font_desc: "Размер текста в советнике",
        set_lang: "Язык (Language)",
        set_lang_desc: "Выберите язык интерфейса",
        chart_dataset: "Набор данных",
        search_loading: "Поиск научных данных...",
        search_analyzing: "Модель анализирует вашу тему.",
        search_err_parse: "Ошибка при обработке данных (JSON Format).",
        search_no_title: "Статья без названия",
        search_no_author: "Неизвестный автор",
        search_no_year: "Год не указан",
        search_read_more: "Читать полностью",
        search_err_fetch: "Не удалось получить статьи с сервера.",
        search_err_network: "Произошла сетевая ошибка.",
        ai_no_response: "Нет ответа.",
        plag_alert_empty: "Введите текст!",
        plag_analyzing: "ИДЕТ АНАЛИЗ...",
        plag_calculating: "Вычисление...",
        plag_searching: "ПОИСК...",
        plag_ai_analyzing: "AI анализирует структуру текста...",
        plag_err_parse: "Не удалось обработать ответ сервера.",
        plag_err_network: "Произошла сетевая ошибка.",
        pub_alert_login: "Для загрузки сначала войдите в личный кабинет!",
        pub_reading: "Чтение файла...",
        pub_uploading: "Файл загружается в облако. Пожалуйста, подождите...",
        pub_success: "Успешно загружено!",
        pub_err_upload: "Не удалось загрузить.",
        pub_err_network: "Ошибка связи.",
        pub_loading: "Загрузка...",
        pub_no_files: "Файлы не загружены.",
        pub_err_fetch: "Не удалось получить данные.",
        pub_download: "Скачать",
        auth_msg_prefix: "Ошибка: ",
        id_prefix: "ID: ",
        info_ph_labels: "Яблоки, Груши, Вишни",
        info_ph_values: "10, 20, 30",
        search_ph_topic: "Искусственный интеллект в медицине...",
        title_calculator: "Фото Калькулятор",
        desc_calculator: "Решение задач по фото (Gemma 4).",
        calc_upload_prompt: "Загрузите или сделайте фото уравнения",
        calc_btn_solve: "РЕШИТЬ ЗАДАЧУ",
        calc_btn_clear: "ОЧИСТИТЬ",
        calc_processing: "Gemma 4 анализирует задачу...",
        calc_result_title: "Подробное решение:",
        calc_err_no_img: "Сначала выберите изображение!",
        calc_tab_stats: "Статистика",
        calc_tab_conv: "Преобразование",
        calc_stats_input: "Данные (через запятую или пробел):",
        calc_btn_run: "Рассчитать",
        calc_conv_type: "Тип:"
    },
    en: {
        app_title: "SCIENTIFIC RESEARCH TECHNOLOGY",
        user_default: "User",
        id_unknown: "ID: Unknown",
        btn_logout: "Logout",
        btn_login_trigger: "Login / Register",
        nav_pubs: "Publications",
        nav_settings: "SETTINGS",
        btn_enter: "ENTER",
        title_query: "Scientific Advisor",
        desc_query: "Solve your questions and doubts.",
        title_methodology: "Methodology Guides",
        desc_methodology: "Learn more about the methodology of scientific projects.",
        title_search: "Project Search",
        desc_search: "Find related research projects.",
        title_plagiarism: "Plagiarism",
        desc_plagiarism: "Check your text for plagiarism.",
        title_infographic: "Infographic Creator",
        desc_infographic: "Create professional charts and diagrams.",
        title_experiments: "Experiment Logs",
        desc_experiments: "Load data and track experiments.",
        auth_title_login: "Login",
        auth_ph_user: "Username",
        auth_ph_pass: "Password",
        auth_btn_login: "Login",
        auth_btn_register: "Register",
        auth_toggle_login: "Already have an account? Login",
        auth_toggle_register: "No account? Register",
        auth_err_fields: "Please fill in all fields.",
        auth_wait: "Please wait...",
        auth_err_server: "An error occurred (No server connection).",
        chat_placeholder: "Enter text...",
        search_title: "Search Articles by Topic",
        search_desc: "Enter a topic to find 5 related academic articles.",
        search_btn: "SEARCH",
        header_methodology: "Writing a Scientific Paper",
        method_s1: "Step 1: Open Problem",
        method_d1: "Formulate the open problem and review literature.",
        method_s2: "Step 2: Thesis",
        method_d2: "Measure relevant processes to build the core paper.",
        method_s3: "Step 3: Methodology Design",
        method_d3: "Prepare baseline models and create a clear scheme.",
        method_s4: "Step 4: Draft Writing",
        method_d4: "Write the first draft of your scientific paper.",
        method_s5: "Step 5: Editing & Formatting",
        method_d5: "Finalize edits and apply standard formatting.",
        plag_card_title: "TEXT CHECK",
        plag_card_desc: "Paste your text below (max 5000 characters).",
        plag_btn: "START CHECK",
        plag_score: "ORIGINALITY",
        plag_status: "WAITING...",
        plag_ai_tips: "AI TIPS",
        header_infographics: "Infographic Builder",
        info_labels: "Data Labels",
        info_values: "Data Values",
        info_type: "Chart Type",
        info_type_bar: "Bar",
        info_type_line: "Line",
        info_type_pie: "Pie",
        info_type_radar: "Radar",
        info_palette: "Color Palette",
        info_btn_dl: "Download PNG",
        header_pubs: "My Publications",
        pubs_drag: "Drag file here or",
        pubs_select: "select",
        pubs_refresh: "Refresh",
        pubs_list: "Files List",
        header_comingsoon: "Coming Soon",
        comingsoon_title: "Soon",
        comingsoon_desc: "This module is under development.",
        header_settings: "Settings",
        set_darkmode: "Dark Mode",
        set_darkmode_desc: "Switch interface to dark colors",
        set_font: "Chat Font",
        set_font_desc: "Text size in scientific advisor",
        set_lang: "Language",
        set_lang_desc: "Select interface language",
        chart_dataset: "Dataset",
        search_loading: "Searching scientific data...",
        search_analyzing: "Model is analyzing your topic.",
        search_err_parse: "Error processing data (JSON Format).",
        search_no_title: "Untitled Article",
        search_no_author: "Unknown Author",
        search_no_year: "Year not specified",
        search_read_more: "Read More",
        search_err_fetch: "Could not fetch articles from server.",
        search_err_network: "Network error occurred.",
        ai_no_response: "No response.",
        plag_alert_empty: "Please enter text!",
        plag_analyzing: "ANALYZING...",
        plag_calculating: "Calculating...",
        plag_searching: "SEARCHING...",
        plag_ai_analyzing: "AI is analyzing text structure...",
        plag_err_parse: "Could not process server response.",
        plag_err_network: "Network error occurred.",
        pub_alert_login: "Please login to your account to upload!",
        pub_reading: "Reading file...",
        pub_uploading: "File is uploading to cloud. Please wait...",
        pub_success: "Successfully uploaded!",
        pub_err_upload: "Upload failed.",
        pub_err_network: "Connection error.",
        pub_loading: "Loading...",
        pub_no_files: "No files uploaded.",
        pub_err_fetch: "Could not fetch data.",
        pub_download: "Download",
        auth_msg_prefix: "Error: ",
        id_prefix: "ID: ",
        info_ph_labels: "Apples, Pears, Cherries",
        info_ph_values: "10, 20, 30",
        search_ph_topic: "Artificial Intelligence in Medicine...",
        title_calculator: "Photo Calculator",
        desc_calculator: "Solve problems via photo (Gemma 4).",
        calc_upload_prompt: "Upload or take a photo of the equation",
        calc_btn_solve: "SOLVE PROBLEM",
        calc_btn_clear: "CLEAR",
        calc_processing: "Gemma 4 is analyzing the problem...",
        calc_result_title: "Detailed Solution:",
        calc_err_no_img: "Please select an image first!",
        calc_tab_stats: "Statistics",
        calc_tab_conv: "Conversions",
        calc_stats_input: "Data (comma or space separated):",
        calc_btn_run: "Calculate",
        calc_conv_type: "Type:"
    }
};

let currentLang = localStorage.getItem('appLang') || 'kk';

function setLanguage(lang) {
    if (!translations[lang]) return;
    currentLang = lang;
    localStorage.setItem('appLang', lang);

    // Update buttons UI
    document.querySelectorAll('.lang-btn').forEach(btn => {
        btn.classList.remove('active');
        if (btn.getAttribute('data-lang') === lang) {
            btn.classList.add('active');
        }
    });

    // Sync settings dropdown if it exists
    const langSelect = document.getElementById('setting-lang-select');
    if (langSelect) {
        langSelect.value = lang;
    }

    // Update all elements with data-i18n
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[currentLang][key]) {
            el.innerHTML = translations[currentLang][key]; // Using innerHTML if icons or formatting exist, otherwise textContent
        }
    });

    // Update placeholders
    const placeholders = document.querySelectorAll('[data-i18n-placeholder]');
    placeholders.forEach(el => {
        const key = el.getAttribute('data-i18n-placeholder');
        if (translations[currentLang][key]) {
            el.placeholder = translations[currentLang][key];
        }
    });

    // Refresh dynamic user UI elements (Name, ID) to avoid overwriting or getting stuck
    if (typeof updateUserUI === 'function') {
        updateUserUI();
    }
}

function t(key) {
    return translations[currentLang][key] || key;
}

document.addEventListener('DOMContentLoaded', () => {
    // Inject data-lang into buttons based on index
    const langBtns = document.querySelectorAll('.lang-btn');
    if(langBtns.length >= 3) {
        langBtns[0].setAttribute('data-lang', 'kk');
        langBtns[1].setAttribute('data-lang', 'ru');
        langBtns[2].setAttribute('data-lang', 'en');
        
        langBtns[0].onclick = () => setLanguage('kk');
        langBtns[1].onclick = () => setLanguage('ru');
        langBtns[2].onclick = () => setLanguage('en');
    }
    
    // Apply init lang
    setLanguage(currentLang);
});
